-- Safe additions for existing installations. Existing nutritionists keep a NULL
-- auth_user_id until they sign in and are linked by email.
ALTER TABLE "NUTRICIONISTA"
  ADD COLUMN IF NOT EXISTS "auth_user_id" UUID;

CREATE UNIQUE INDEX IF NOT EXISTS "NUTRICIONISTA_auth_user_id_key"
  ON "NUTRICIONISTA" ("auth_user_id");

ALTER TABLE "NUTRICIONISTA"
  ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "PACIENTE"
  ADD COLUMN IF NOT EXISTS "auth_user_id" UUID,
  ADD COLUMN IF NOT EXISTS "email" TEXT,
  ADD COLUMN IF NOT EXISTS "telefono" TEXT,
  ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX IF NOT EXISTS "PACIENTE_auth_user_id_key"
  ON "PACIENTE" ("auth_user_id");
